services:
  - docker

sudo: required

branches:
  only:
  - develop
  - master

before_install:
  - sudo docker pull ubuntu:xenial
  - sudo docker build -t rcldocker .

before_script:
  - sudo apt-get install google-chrome-stable
  - sudo apt-get install libxtst6
  - sudo apt-get install libxtst6:i386
  - sudo apt-get install libxext6
  - sudo updatedb
  - locate libXtst

script:
  - sudo docker run -v $(pwd):/root/ros2-web-bridge --rm rcldocker bash -i -c 'cd /root/ros2-web-bridge && npm install --unsafe-perm && npm run ci example.html'

